dfki_scorecard:
    resource: "@DFKIScorecardBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    
#REST 
rest : 
  type : rest 
  resource : "@DFKIScorecardBundle/Resources/config/routing_rest.yml"
  prefix : /api